### ISSUE TITLE
throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");

### ISSUE THREAD

**Issue by alan6122** [huangshuwei/vue-easytable#114]
```javascript
60/62 modules 2 active ...ct/vue/my-project/src/assets/logo.png/Users/alan/Documents/hfwork/ResearchProject/vue/my-project/node_modules/loader-runner/lib/loadLoader.js:35
                        throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");
                        ^

Error: Module '/Users/alan/Documents/hfwork/ResearchProject/vue/my-project/node_modules/url/url.js' is not a loader (must have normal or pitch function)
    at loadLoader (/Users/alan/Documents/hfwork/ResearchProject/vue/my-project/node_modules/loader-runner/lib/loadLoader.js:35:10)
    at iteratePitchingLoaders (/Users/alan/Documents/hfwork/ResearchProject/vue/my-project/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/alan/Documents/hfwork/ResearchProject/vue/my-project/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/alan/Documents/hfwork/ResearchProject/vue/my-project/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/alan/Documents/hfwork/ResearchProject/vue/my-project/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/alan/Documents/hfwork/ResearchProject/vue/my-project/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/alan/Documents/hfwork/ResearchProject/vue/my-project/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/alan/Documents/hfwork/ResearchProject/vue/my-project/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/Users/alan/Documents/hfwork/ResearchProject/vue/my-project/node_modules/webpack/lib/NormalModule.js:275:15)
    at Compilation.buildModule (/Users/alan/Documents/hfwork/ResearchProject/vue/my-project/node_modules/webpack/lib/Compilation.js:151:10)
    at factoryCallback (/Users/alan/Documents/hfwork/ResearchProject/vue/my-project/node_modules/webpack/lib/Compilation.js:342:12)
```

**Comment by huangshuwei** [comment]
能否具体的提供下出现这个错误的场景，是打包的时候吗

**Comment by ly525** [comment]
暂时关闭，麻烦提供出错的场景。
